"""add_child_and_assignments

Revision ID: c32d54e626d8
Revises: 4a0f47b1b258
Create Date: 2026-07-31 21:14:26.193871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c32d54e626d8'
down_revision: Union[str, Sequence[str], None] = '4a0f47b1b258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('children',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('difficulty_level', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id', 'child_id', name='uq_material_child_assignment')
    )
    op.add_column('materials', sa.Column('subject', sa.String(length=50), server_default='General', nullable=False))
    op.add_column('submissions', sa.Column('child_id', sa.UUID(), nullable=True))
    op.add_column('submissions', sa.Column('difficulty_level', sa.String(length=20), nullable=True))
    op.create_foreign_key(None, 'submissions', 'children', ['child_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.drop_column('submissions', 'difficulty_level')
    op.drop_column('submissions', 'child_id')
    op.drop_column('materials', 'subject')
    op.drop_table('material_assignments')
    op.drop_table('children')
    # ### end Alembic commands ###
